[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.21.0", features = ["csr"] }
web-sys = "0.3.69"
chrono = "0.4.38"
futures = "0.3.30"
common = { path = "../common"}
anyhow = "1.0.86"