[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1", features = ["full"]}
serde = {version = "1.0.202", features = ["derive"] }
rmp-serde = "1.3.0"
surrealdb = "1.5.0"
anyhow = "1.0.86"
common = { path = "../common"}
